apiVersion: apps/v1
kind: Deployment
metadata:
  name:  geoserver
  namespace: geoserver-cluster
  labels:
    app:  geoserver
spec:
  selector:
    matchLabels:
      app: geoserver
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  geoserver
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  geoserver
        image:  home-docker.sandbox.local:5000/geoserver:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 200m
            memory: 1000Mi
        ports:
        - containerPort:  8080
          name:  geoserver
        # volumeMounts:
        # - name: brokerproperties
        #   mountPath: /geoserver/data_dir/cluster/cluster.properties
        #   subPath: cluster.properties        
        command: ["/bin/bash","-c"]
        args: ['sed -i "s/instanceName=/instanceName=$(hostname)/g" /geoserver/data_dir/cluster/cluster.properties; /geoserver/bin/startup.sh;']
      volumes:
        - name: brokerproperties
          secret:
            secretName: brokerproperties
      restartPolicy: Always