apiVersion: v1
kind: Service
metadata:
  name: activemq
  namespace: geoserver-cluster
spec:
  selector:
    app: activemq
  type: NodePort
  ports:
  - name: dashboard
    port: 8161
  - name: openwire
    port: 61616

